<?php

namespace App\Models;

use App\Models\Traits\ActiveArticleHelper;
use Dcat\Admin\Traits\HasDateTimeFormatter;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Dcat\Admin\Widgets\Markdown;
use Dcat\Admin\Widgets\Card;

class Article extends Model
{
	use HasDateTimeFormatter;
    use SoftDeletes;
    use ActiveArticleHelper;
    use HasFactory;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function ($model) {
            $model->content_html = Card::make(Markdown::make($model->content));
            $model->introduction = mb_substr(strip_tags($model->content_html), 0, 100);
        });
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'type', 'id');
    }

    public function tag()
    {
        return $this->belongsToMany(Tag::class);
    }
}
